name: adversarial

channels:
  - pytorch
  - conda-forge
  - pytorch-lts

dependencies:
  - python>=3.6.9
  - numpy=1.21.5
  - scipy=1.4.1
  - matplotlib=3.2.2
  - scikit-learn=1.0.2
  - pytorch=1.10.0
  - torchvision=0.11.1
  - opencv=4.1.2
  - pandas
  - tqdm
  - pip
  - pip:
    - argparse
    - torchattacks